### ISSUE TITLE
wallet unlock fails

### ISSUE THREAD

**Issue by edmundspriede** [WaltonChain/WaltonWallet#1]
it used to work , but now i cannot unlock wallet on Win 10 latest updates, ESET Endpoint security.

when unlocking wallet WaltonWallet.exe stops responding

OS build 16299.125   Version 1709

**Comment by WaltonChain** [comment]
You can try to close ESET temporarily and run WaltonWallet.exe again. Wish to hear from your more information.

**Comment by edmundspriede** [comment]
works today with ESET ... possibly some deadly combination of AV and Defender...
