### ISSUE TITLE
Network Load

### ISSUE THREAD

**Issue by maddoc41** [WaltonChain/WaltonWallet#3]
I have been testing the new Wallet ever since it has been released. I also watched the network load and compared it to other miners. Interestingly, ccminer uses about 4-5 mb/h summing up to about 100 mb/d, while Walton Wallet adds an additional 35 mb/h which seems pretty much to me. Any thoughts or ideas?

**Comment by samsson** [comment]
ccminer is just a miner to my knowledge. The Walton.exe acts as a full node at the same time, hence the network traffic increase.

**Comment by WaltonChain** [comment]
as @samsson says.
