### ISSUE TITLE
Mining Tokens Issue

### ISSUE THREAD

**Issue by pmtolk** [WaltonChain/WaltonWallet#4]
Hi, I am testing the beta wallet and mining and I have mined about 5000+ blocks but have not gotten any test wtc tokens and I am wondering what I am doing wrong? 

How can I designate which wallet the miner is going to send the mining rewards to?

And where can I see how much rewards I have mined per hour, per day, total etc?

**Comment by maddoc41** [comment]
Under Settings you Can Change The miner adress. Marke sure it Matches your Public key.

**Comment by pmtolk** [comment]
When I try to load my wallet using the keystore and password, it gets to the syncing wallet and then crashes 
Unhandled exception at 0x00007FFF560D350E (ucrtbase.dll) in WaltonWallet.exe: Fatal program exit requested.

**Comment by pmtolk** [comment]
The issue is using a vpn. Without a vpn, I the wallet and mining are working.

**Comment by PtrJung** [comment]
This is my first time mining and I would like to echo pmtolk's questions regarding how you can track the blocks that you yourself have mined. 

Also, a date/time stamp would be nice to see on the list.

**Comment by raul602** [comment]
@pmtolk  As you stated the issue appears when it's having a connection issue with WTC, I have noticed this as well when I discovered my work was blocking traffic to China.

**Comment by CryptoRALLY** [comment]
@PtrJung  - Having that in the wallet would def be nice, keep in mind you can also use waltonchain.net and search for your miner address and you should be able to find this info there.

**Comment by PtrJung** [comment]
Thanks for that link @CryptoRALLY

**Comment by PtrJung** [comment]
One more issue. The wallet seems to be having problems detecting nodes. Am I actually mining if no nodes?
![walton wallet](https://user-images.githubusercontent.com/35774297/35392005-60b94a7a-01ae-11e8-9659-d1a1e7b9d86b.jpg)

**Comment by WaltonChain** [comment]
If you connect to no nodes, it means you are mining your private chain. Once you have connected to nodes, our program continues mining the main chain. So do not worry, just wait until it connects to at least one node.
