### ISSUE TITLE
Stack Buffer Overrun.

### ISSUE THREAD

**Issue by samsson** [WaltonChain/WaltonWallet#5]
There is an issue when trying to open a keystore file while the internet connection is not working.
It runs for a while and crashes with "stack_buffer_overrun" exception.

"Traceback (most recent call last):\n  File \"WaltonWallet.py\", line 1527, in thread_refresh\nAttributeError: 'Worker' object has no attribute 'result4'"

Steps to reproduce:
Open WaltonWallet.exe
Make sure your internet connection is not working (default gateway not reachable but address is known)
Click view Wallet and unlock wallet with keystore.
Choose keystore.
Enter password and click unlock.
Wait for wallet to crash.

Edit: issue with at least latest version v1.3.0
Edit: from mining attempt without network:
"Traceback (most recent call last):\n  File \"WaltonWallet.py\", line 1607, in refreshHashrate\nAttributeError: 'RefreshHash' object has no attribute 'result3'"

**Comment by samsson** [comment]
Same issue when trying to start mining. Seems like other folks have this issue as well, when having network problems or using vpn etc.

**Comment by WaltonChain** [comment]
We have notice this issue, we will try to solve this problem in next version.
Thanks a lot.
