### ISSUE TITLE
No. of Threads

### ISSUE THREAD

**Issue by redrocketgt** [WaltonChain/WaltonWallet#6]
In v 1_3_0 the number of threads is limited to 10 in the GUI.

What happens if a CPU is capable of more than 10 threads?

Does the wallet take advantage of Dual CPUs?

**Comment by WaltonChain** [comment]
We have noticed this issue and we are testing gpu mining system. In the future, gpu may be the greatest way in mining. We will also support dual cpus afterwards. Thank you for your advice.
