### ISSUE TITLE
WaltonWallet.exe has stopped working

### ISSUE THREAD

**Issue by asebak** [WaltonChain/WaltonWallet#7]
Getting this error whenever i try to unlock the wallet or start mining.  Anyway I can view the logs of what is going on.

![image](https://user-images.githubusercontent.com/2384411/37242757-a69de73e-243c-11e8-8ad9-341cc95a78d2.png)

**Comment by asebak** [comment]
More Details:

Unhandled exception at 0x00007FFD9BCFB79E (ucrtbase.dll) in WaltonWallet.exe: Fatal program exit requested.

**Comment by alien4847** [comment]
Same problem here. Was working fine for weeks!

**Comment by cafemotocb** [comment]
I have this issue as well in Server 2016.

Faulting application name: WaltonWallet.exe, version: 0.0.0.0, time stamp: 0x597f4a43
Faulting module name: ucrtbase.dll, version: 10.0.14393.2097, time stamp: 0x5a820a13
Exception code: 0xc0000409
Fault offset: 0x000000000006eabe
Faulting process id: 0x1230
Faulting application start time: 0x01d3bf136291d3b7
Faulting application path: C:\WaltonWallet\WaltonWallet.exe
Faulting module path: C:\Windows\System32\ucrtbase.dll
Report Id: b19e7807-0140-47f8-91ca-8de0720e0e91
Faulting package full name: 
Faulting package-relative application ID:

**Comment by ssaip** [comment]
I think the testnet is currently down (due to transition to mainnet?)
